/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import Classes.*;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 * @date created 23/11/2017 
 * @date commented 18/2/2018
 * @author Stuart Reid
 * Class defining an instance of our Customer Home page.
 */
public class CustomerHome extends javax.swing.JFrame {

    //attributes
    
    //global variable holding our logged in customer
    Customer cust;

    //global variable holding our users basket
    HashMap<Integer, OrderLine> basket;

    
    /**
     * Creates new form CustomerHome
     * initialises form components
     */
    public CustomerHome() {
        initComponents();
    }
    
    
    /**
     * Creates new form CustomerHome
     * initialises form components
     * maps customer parameter to our global variable
     * sets our welcome label with custom welcome message
     * @param cust - parameter holding our logged in user
     */
    public CustomerHome(Customer cust) {
        initComponents();
        this.cust = cust;
        welcomeLbl.setText(this.cust.displayGreeting());
    }
    
    
    /**
     * Creates new form CustomerHome
     * initialises form components
     * maps customer parameter to our global variable
     * maps our basket parameter to our basket global variable
     * sets our welcome label with custom welcome message
     * @param cust - parameter holding our logged in user
     * @param basket - parameter passed in holding a hashmap of orderlines representing users shopping basket
     */
    public CustomerHome(Customer cust, HashMap<Integer, OrderLine> basket)
    {
        initComponents();
        this.cust = cust;
        this.basket = basket;
        welcomeLbl.setText(this.cust.displayGreeting());
    }


    
    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLbl = new javax.swing.JLabel();
        browseBtn = new javax.swing.JButton();
        viewOrdersBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        unregBn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 600));

        welcomeLbl.setText("Welcome");

        browseBtn.setText("BROWSE PRODUCTS");
        browseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseBtnActionPerformed(evt);
            }
        });

        viewOrdersBtn.setText("VIEW MY ORDERS");
        viewOrdersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrdersBtnActionPerformed(evt);
            }
        });

        editBtn.setText("EDIT DETAILS");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        unregBn.setText("UNREGISTER FROM SHOP");
        unregBn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unregBnActionPerformed(evt);
            }
        });

        logoutBtn.setText("LOG OUT");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(welcomeLbl)
                .addContainerGap(174, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addComponent(browseBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewOrdersBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(unregBn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeLbl)
                .addGap(18, 18, 18)
                .addComponent(browseBtn)
                .addGap(18, 18, 18)
                .addComponent(viewOrdersBtn)
                .addGap(18, 18, 18)
                .addComponent(editBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(unregBn)
                .addGap(18, 18, 18)
                .addComponent(logoutBtn)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * on click event for our edit button
     * @param evt 
     */
    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        //creates instance of our Edit Details form passing in our logged in customer and their basket
        EditDetails edt = new EditDetails(cust, basket);
        //closes current form
        this.dispose();
        //sets new form to visible
        edt.setVisible(true);
    }//GEN-LAST:event_editBtnActionPerformed

    
    /**
     * on click event for un registering our logged in user
     * @param evt 
     */
    private void unregBnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unregBnActionPerformed
        
        //creating a confirmation dialogue and storeing the result to int o
        int o = JOptionPane.showConfirmDialog(null, "This will permanently delete your account!\nDo you wish to continue?","DELETE USER!",JOptionPane.YES_NO_OPTION);
                
        //if user selects yes
        if(o == 0)
        {
            //changels the welcome label text
            welcomeLbl.setText("You heve been de-registered!");
            //creates instance of our database manager class
            DBManager db = new DBManager();
            //calls delete customer method on dbmanager passing in the logged in customer
            db.deleteCustomer(cust);

            //displays pop up message with confirmation of delete
            infoBox("Your profile has been deleted!\nClose this window to continue.","USER STATUS");

            //creates new instance of our main menu
            Menu mnu = new Menu();
            //closes current form
            this.dispose();
            //makes new form visible
            mnu.setVisible(true);
        }
    }//GEN-LAST:event_unregBnActionPerformed

    
    /**
     * on click event for our browse button
     * @param evt 
     */
    private void browseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBtnActionPerformed
        //creates new instance of our view product form passing in our logged in customer and their shopping basket
        ViewProducts view = new ViewProducts(cust, basket);
        //closes current form
        this.dispose();
        //sets new form to visible
        view.setVisible(true);
    }//GEN-LAST:event_browseBtnActionPerformed

    
    /**
     * on click event for our log out button
     * @param evt 
     */
    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        //sets cust global variable to null
        cust = null;
        //creates pop up with confirmation
        infoBox("You have been logged out!\nClose this window to return to the main menu.","USER STATUS");
        //creates new instance of our main menuform passing in a null valued customer as a parameter
        Menu mnu = new Menu(cust);
        //closes current form
        this.dispose();
        //makes new form visible
        mnu.setVisible(true);
    }//GEN-LAST:event_logoutBtnActionPerformed

    
    /**
     * on click event for our view orders button
     * @param evt 
     */
    private void viewOrdersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrdersBtnActionPerformed
        //creates new instance of our view orders form passing in our logged in customer and their shopping basket
        ViewOrders viewO = new ViewOrders(cust, basket);
        //closes current form
        this.dispose();
        //sets new form to visible
        viewO.setVisible(true);
    }//GEN-LAST:event_viewOrdersBtnActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerHome().setVisible(true);
            }
        });
    }

    
    /**
     * Method defining our pop up box
     * @param infoMessage - holds the body of our message
     * @param titleBar  - holds the title of the info box
     */
    public static void infoBox(String infoMessage, String titleBar)
    {
        JOptionPane.showMessageDialog(null, infoMessage, "InfoBox: " + titleBar, JOptionPane.INFORMATION_MESSAGE);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton unregBn;
    private javax.swing.JButton viewOrdersBtn;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}
