/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.Clothing;
import Classes.DBManager;
import Classes.Footwear;
import Classes.Product;
import Classes.Staff;
import static GUI.EditDetails.infoBox;
import javax.swing.JOptionPane;


/**
 * @Date 18/2/2018 - commented class - sr
 * @author StuartR
 */
public class EditProduct extends javax.swing.JFrame {

    //global variable holding our product
    Product p;
    //boolean holding whither or not the item is an article of clothing
    boolean clothing;
    //our logged in staff member
    Staff staff;
    
    
    /**
     * Creates new form EditProduct
     */
    public EditProduct() {
        initComponents();
    }
    
    
    /**
     * Overloaded constructor creating new EditProduct form
     * @param p - this stores the product we are editing
     * @param staff - our logged in staff member
     * @param clothing - boolean value confirming if product is an item of clothing
     * initialises components
     * maps parameter values to our global variables
     * calls our fillIn method to populate data
     */
    public EditProduct(Product p, Staff staff, boolean clothing)
    {
        initComponents();
        this.p = p;
        this.staff = staff;
        this.clothing = clothing;
        
        fillIn();
    }

    
    /**2
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        idLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        priceLbl = new javax.swing.JLabel();
        stockLbl = new javax.swing.JLabel();
        varLbl = new javax.swing.JLabel();
        idTxtBx = new javax.swing.JTextField();
        priceTxtBx = new javax.swing.JTextField();
        nameTxtBx = new javax.swing.JTextField();
        varTxtBx = new javax.swing.JTextField();
        stockTxtBx = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        submitBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("EDIT PRODUCT DETAILS");

        idLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        idLbl.setText("ID:");

        nameLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nameLbl.setText("NAME:");

        priceLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        priceLbl.setText("PRICE: £");

        stockLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        stockLbl.setText("STOCK LEVEL:");

        varLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        varLbl.setText("MEASUREMENT:");

        backBtn.setText("RETURN TO PRODUCT SELECT");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        submitBtn.setText("SUBMIT CHANGES");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("CLEAR CHANGES");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stockLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(varLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(varTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stockTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 113, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(submitBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(titleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clearBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLbl)
                    .addComponent(idTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLbl)
                    .addComponent(nameTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLbl)
                    .addComponent(priceTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stockLbl)
                    .addComponent(stockTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varLbl)
                    .addComponent(varTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(submitBtn)
                .addGap(53, 53, 53)
                .addComponent(clearBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * on click event for our clear button
     * cals our fill in method to return screen to products current values
     * @param evt 
     */
    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        fillIn();
    }//GEN-LAST:event_clearBtnActionPerformed

    
    /**
     * on click event for our back button
     * @param evt 
     */
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        //creates an instance of our staff view products page passing in our logged in staff member
        StaffViewProducts svp = new StaffViewProducts(staff);
        //closes current form
        this.dispose();
        //sets new form to visible
        svp.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    
    /**
     * on click event for our submit button
     * @param evt 
     */
    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        
        //creating a confirmation dialogue and storeing the result to int o
        int o = JOptionPane.showConfirmDialog(null, "This will permanently ammend this product in your range!\nDo you wish to continue?","AMMEND PRODUCT!",JOptionPane.YES_NO_OPTION);
        
        //if user selects yes
        if(o == 0)
        {
            //if any of the feilds have not been completed
            if(varTxtBx.getText().equals("") ||
            nameTxtBx.getText().equals("") ||
            priceTxtBx.getText().equals("") ||
            stockTxtBx.getText().equals(""))
            {
                //error pop up
                infoBox("Please complete all fields before attempting to add an item!","ITEM ERROR");
            }
            //if all feilds have data in them
            else
            {
                //if name and var text feilds are within allowed character values
                if(validateLength(0,20,nameTxtBx.getText()) == true  || validateLength(0,20,varTxtBx.getText()) == true)
                {
                    //creates a new instance of our db manager class
                    DBManager db = new DBManager();

                    try{
                        //attempts to pasre our user input to a double variable
                        Double price = Double.parseDouble(priceTxtBx.getText());
                        try{
                            //attempts to parse our user input to an integer variable
                            int stock = Integer.parseInt(stockTxtBx.getText());

                            //if the item is an article of clothing
                            if(clothing)
                            {                    
                                //create new instance of clothing item with overloaded constructor passin in user input
                                Clothing cl = new Clothing(Integer.parseInt(idTxtBx.getText()), nameTxtBx.getText(), price, stock, varTxtBx.getText());
                                //calls db manager method to update item in database
                                db.updateClothingItem(cl);
                                //pop up confirmation messsage
                                infoBox("Item has been updated!","ITEM AMENDED");
                            }
                            //if the item is from the footwear range
                            else
                            {
                                try{
                                    //we attempt to parse the user input to an integer variable
                                    int size = Integer.parseInt(varTxtBx.getText());
                                    //creates new instance of our footwear class using user input with our overloaded contructor
                                    Footwear ft = new Footwear(Integer.parseInt(idTxtBx.getText()), nameTxtBx.getText(), price, stock, size);
                                    //calls our db method to update the item in the database
                                    db.updateFootwearItem(ft);
                                    //pop up confirmation
                                    infoBox("Item has been updated!","ITEM AMENDED");
                                } catch(Exception e){
                                    // if the size input is not in the correct format
                                    infoBox("Please only enter a numeric value for the item size!","INPUT ERROR");
                                }

                            }
                        }catch (Exception e){
                            //if the stock level user input is not in the correct format
                            infoBox("Please only enter a numeric value for a stock level!","INPUT ERROR");
                        }
                    }catch (Exception e) {
                        //if the price user input is not in the correct format
                        infoBox("Please only enter a numeric value for the item price!","INPUT ERROR");
                    }
                } 
                //if name and var feild excede allowed charcters
                else
                {
                    //error message pop up
                    infoBox("Please ensure that the following collumns do not excede the maximum number of characters\n Name max: 20\nMeasurement max: 20","INPUT ERROR");
                }
            }
        }
    }//GEN-LAST:event_submitBtnActionPerformed

    
    /**
     * A method to for user input validation
     * @param min - int holding our minimum required length for our string
     * @param max - int holding the maximum required length for our string
     * @param input - the string we will be testing
     * @return - returns true if string is the correct length
     */
    public boolean validateLength(int min, int max, String input)
    {
        if(input.length() <= max && input.length() >= min)
        {
            return true;
        }
        else
        {
            return false;
        }
    }
    
    
    /**
     * method used to populate form with global products values
     */
    private void fillIn() 
    {
        //set id and disable user interaction
        idTxtBx.setText("" + p.getProductID());
        idTxtBx.setEnabled(false);
        //set name
        nameTxtBx.setText(p.getProductName());
        //set price in correct format
        priceTxtBx.setText("" + String.format("%.2f", p.getPrice()));
        //set stock level
        stockTxtBx.setText("" + p.getStockLevel());
        //if clothing
        if(clothing)
        {
            //cast product to clothing subclass
            Clothing c = (Clothing)p;
            //set var feild
            varTxtBx.setText(c.getMeasurement());
        }
        //if footwear
        else
        {
            //cast product to footwear subclass
            Footwear f = (Footwear)p;
            //set var label text
            varLbl.setText("SIZE:");
            //set size 
            varTxtBx.setText("" + f.getSize());
        }
    }
    
    
    /**
     * Method defining our pop up box
     * @param infoMessage - holds the body of our message
     * @param titleBar  - holds the title of the info box
     */
    public static void infoBox(String infoMessage, String titleBar)
    {
        JOptionPane.showMessageDialog(null, infoMessage, "InfoBox: " + titleBar, JOptionPane.INFORMATION_MESSAGE);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditProduct().setVisible(true);
            }
        });
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel idLbl;
    private javax.swing.JTextField idTxtBx;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTxtBx;
    private javax.swing.JLabel priceLbl;
    private javax.swing.JTextField priceTxtBx;
    private javax.swing.JLabel stockLbl;
    private javax.swing.JTextField stockTxtBx;
    private javax.swing.JButton submitBtn;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel varLbl;
    private javax.swing.JTextField varTxtBx;
    // End of variables declaration//GEN-END:variables
}
