/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import Classes.*;

/**
 * @date 13/11/2017
 * @date commented 19/2/2018
 * @author Stuart Reid
 * Class defining an instance of our main menu page.
 */
public class Menu extends javax.swing.JFrame {

    //global variable holding a logged in user
    Customer cust;


    /**
     * Creates new form Menu and initialises components
     */
    public Menu() {
        initComponents();
    }
    

    /**
     * Creates new for taking in an instance of customer class
     * initialises components
     * @param cust - passed in instance of our customer class representing the logged in user
     */
    public Menu(Customer cust){
        initComponents();
        this.cust = cust;
    }
    
    
    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuLbl = new javax.swing.JLabel();
        customerLoginBtn = new javax.swing.JButton();
        staffLoginBtn = new javax.swing.JButton();
        viewProductBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 600));
        setResizable(false);

        menuLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuLbl.setText("MAIN MENU");

        customerLoginBtn.setText("CUSTOMER LOGIN");
        customerLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerLoginBtnActionPerformed(evt);
            }
        });

        staffLoginBtn.setText("STAFF LOGIN");
        staffLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffLoginBtnActionPerformed(evt);
            }
        });

        viewProductBtn.setText("VIEW PRODUCTS");
        viewProductBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProductBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewProductBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(staffLoginBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerLoginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(menuLbl)
                .addGap(18, 18, 18)
                .addComponent(customerLoginBtn)
                .addGap(18, 18, 18)
                .addComponent(staffLoginBtn)
                .addGap(18, 18, 18)
                .addComponent(viewProductBtn)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * on click for our staff login button
     * @param evt 
     */
    private void staffLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffLoginBtnActionPerformed
        //creates instance of our staff log in form
        StaffLogin sl = new StaffLogin();
        //closes current form
        this.dispose();
        //sets new form to visible
        sl.setVisible(true);
    }//GEN-LAST:event_staffLoginBtnActionPerformed

    
    /**
     * on click for our customer log in button
     * @param evt 
     */
    private void customerLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerLoginBtnActionPerformed
        //if customer is currently logged in
        if (cust != null)
        {
            //error message
            menuLbl.setText("Please log out of account!");
        }
        //if no logged in customer
        else
        {
            //creates new instance of our log in page
            CustomerLogin login = new CustomerLogin();
            ///closes current form
            this.dispose();
            //sets new form to visible
            login.setVisible(true);
        }
    }//GEN-LAST:event_customerLoginBtnActionPerformed

    
    /**
     * on click for our view products page
     * @param evt 
     */
    private void viewProductBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProductBtnActionPerformed
        //if customer is currently logged in
        if (cust != null)
        {
            //creates new instance of our view products form
            ViewProducts vp = new ViewProducts();
            //closes current form
            this.dispose();
            //sets new for to visible
            vp.setVisible(true);
        }
        else
        {
            //creates new instance of our view products form passing in our cust global variale
            ViewProducts vp = new ViewProducts(cust);
            //closes current form
            this.dispose();
            //sets new for to visible
            vp.setVisible(true);
        }
    }//GEN-LAST:event_viewProductBtnActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton customerLoginBtn;
    private javax.swing.JLabel menuLbl;
    private javax.swing.JButton staffLoginBtn;
    private javax.swing.JButton viewProductBtn;
    // End of variables declaration//GEN-END:variables
}
