/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.Order;
import Classes.OrderLine;
import Classes.Staff;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;

/**
 * @date 21/02/2018 - commented class - sr
 * @author Stuart Reid
 */
public class StaffViewAnOrder extends javax.swing.JFrame {

    //global variable to hold our logged in staff member
    Staff staff;
    //global variable holding the order we wish to view
    Order order;
    
    
    /**
     * Creates new form StaffViewAnOrder
     * initialises components
     */
    public StaffViewAnOrder() {
        initComponents();
    }

    
    /**
     * overloaded constructor creating an instance of our view an order form
     * initialises components and maps parameters to our global variables
     * @param staff - parameter holding our logged in customer
     * @param order - parameter holding our order that we wish to view
     * calls fill table method
     */
    public StaffViewAnOrder(Staff staff, Order order)
    {
       initComponents();
       this.staff = staff;
       this.order = order;
       fillTable();
    }
    

    /**
     * method that fills our table with the details of our order
     */
    private void fillTable()
    {
        //creates a default table manager and pulls the table model from our gui
        DefaultTableModel dtm = (DefaultTableModel)orderTbl.getModel();
        //hash map holding our orderlines
        HashMap<Integer, OrderLine> orderLines = order.getOrderLines();
        
        //for each orderline in our hashmap
        for(Integer key : orderLines.keySet())
        {
            //creating an array of strings
            String[] data = new String[4];
            //mapping total price of orderline to a double variable
            double price = orderLines.get(key).getLineTotal();
            //filling each element of our array with the orderline values
            data[0] = "" + orderLines.get(key).getProduct().getProductID();
                    
            data[1] = "" + orderLines.get(key).getProduct().getProductName();
            
            data[2] = "£" + String.format("%.2f", price);

            data[3] = "" + orderLines.get(key).getQuantity();
            //adding array to our table model
            dtm.addRow(data);
        }
        //setting table model to our table 
        orderTbl.setModel(dtm);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderTbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backBtn.setText("RETURN TO ORDERS");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        orderTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCT ID", "PRODUCT", "PRICE", "QUANTITY"
            }
        ));
        jScrollPane1.setViewportView(orderTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBtn)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * on click for our back button
     * @param evt 
     */
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        //creates a staff view orders form passing in our logged in staff member
        StaffViewOrders svo = new StaffViewOrders(staff);
        //closing existing form
        this.dispose();
        //setting new form to visible
        svo.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffViewAnOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffViewAnOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffViewAnOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffViewAnOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffViewAnOrder().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable orderTbl;
    // End of variables declaration//GEN-END:variables
}
