/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.*;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * @date 22/02/2018 - commented - sr
 * @author Stuart Reid
 */
public class ViewOrders extends javax.swing.JFrame {

    //global variable holding our logged in customer
    Customer cust;
    //global variable holding our shopping basket
    HashMap<Integer, OrderLine> basket;
    
    
    /**
     * Creates new form ViewOrders
     * initialises components and fills data
     */
    public ViewOrders() {
        initComponents();
        if (!cust.getOrders().isEmpty() || cust.getOrders() != null)
        {
        fillTable();
        }
    }
    
    
    /**
     * Creates new form ViewOrders
     * @param cust takes in our logged in customer as a parameter
     * initialises components and if the customer has any orders the table is filled
     * maps parameter to global variable
     */
    public ViewOrders(Customer cust)
    {
        initComponents();
        this.cust = cust; 
        if (!cust.getOrders().isEmpty() || cust.getOrders() != null)
        {
        fillTable();
        }
    }
    
    
    /**
     * Creates new form ViewOrders
     * initialises components and if the customer has any orders the table is filled
     * maps parameters to global variables
     * @param cust takes in our logged in customer as a parameter
     * @param basket takes in our basket - not used in this class but for continuity
     */
    public ViewOrders(Customer cust, HashMap<Integer, OrderLine> basket)
    {
        initComponents(); 
        this.cust = cust; 
        this.basket = basket; 
        if (!cust.getOrders().isEmpty() || cust.getOrders() != null)
        {
        fillTable();
        }
    }
    
    /**
     * method to fill data in to our table
     */
    private void fillTable()
    {
        //creates default table model and pulls the existing model from our table entity
        DefaultTableModel dtm = (DefaultTableModel)orderTbl.getModel();
        //creates a hashmap pulling in the customers order attribute
        HashMap<Integer, Order> orders = cust.getOrders();
        
        //for each order in our hashmap
        for(Integer key : orders.keySet())
        {
            //creating array and setting values to the arrays elements
            String[] data = new String[3];
            double price = orders.get(key).getOrderTotal();
            data[0] = "" + orders.get(key).getOrderID();
            data[1] = "" + orders.get(key).getOrderDate();
            data[2] = "£" + String.format("%.2f", price);
            //adding array to a row in our table model
            dtm.addRow(data);
        }
        //setting table model to our table entity
        orderTbl.setModel(dtm);
    }
    
    
    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderTbl = new javax.swing.JTable();
        ViewOrderBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 600));

        backBtn.setText("RETURN TO CUSTOMER HOME");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        orderTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order Number", "Date", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(orderTbl);

        ViewOrderBtn.setText("VIEW SELECTED ORDER");
        ViewOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewOrderBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBtn)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ViewOrderBtn)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * on click for our back button
     * @param evt 
     */
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        //creates new customer home form passing in our logged in customer and our shopping basket
        CustomerHome cHome = new CustomerHome(cust, basket);
        //closes existing form
        this.dispose();
        //sets new form to visible
        cHome.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    
    /**
     * on click for our view an order button
     * @param evt 
     */
    private void ViewOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewOrderBtnActionPerformed
        //if there is a row selected
        if(orderTbl.getSelectedRow() != -1)
        {
            //creates default table model and pulls the existing model from our table entity
            DefaultTableModel dtm = (DefaultTableModel)orderTbl.getModel();
            //creates in setting it to the selected row index
            int row = orderTbl.getSelectedRow();
            //pulls the data at our id collum for our specified row and maps it to a string variable
            String idValue = dtm.getValueAt(row, 0).toString();
            //parses our string in to an integer
            int id = Integer.parseInt(idValue);

            //creates an order mapping it to the item in our orders hashmap with the matching id
            Order order = cust.getOrders().get(id);
            //creates new view  an order form passing in our logged in customer, the order we wish to view and our shopping basket
            ViewAnOrder vao = new ViewAnOrder(cust, order, basket);
            //closes existing form
            this.dispose();
            //sets new form to visible
            vao.setVisible(true);
        }
        //if nothing selected
        else
        {
            //error message pop up
            infoBox("Please select the order you would like to view!","ORDERS");
        }
    }//GEN-LAST:event_ViewOrderBtnActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewOrders().setVisible(true);
            }
        });
    }


    /**
     * Method defining our pop up box
     * @param infoMessage - holds the body of our message
     * @param titleBar  - holds the title of the info box
     */       
    public static void infoBox(String infoMessage, String titleBar)
    {
        JOptionPane.showMessageDialog(null, infoMessage, "InfoBox: " + titleBar, JOptionPane.INFORMATION_MESSAGE);
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ViewOrderBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable orderTbl;
    // End of variables declaration//GEN-END:variables
}
