/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.*;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;

/**
 * @date 22/02/2018 - commented - sr
 * @author Stuart Reid
 */
public class ViewAnOrder extends javax.swing.JFrame {

    //global variable holding our logged in customer
    Customer cust;
    //global variable holding the order we wish to view
    Order order;
    //global variable holding a hashmap of orderlines that represents our shopping cart
    HashMap<Integer, OrderLine> basket;
    
    
    /**
     * Creates new form ViewAnOrder
     * initialises components
     */
    public ViewAnOrder() {
        initComponents();
    }

    
    /**
    * Creates new form ViewAnOrder
    * initialises components
    * maps parameters to global variables
    * calls fill table method
    * @param cust - parameter holding our logged in customer
    * @param order - parameter holding the order we wish to view
    * @param basket - parameter holding a hashmap of orderlines that represents our shopping cart
    */   
    public ViewAnOrder(Customer cust, Order order, HashMap<Integer, OrderLine> basket)
    {
        initComponents();
        this.cust = cust;
        this.order = order;
        this.basket = basket;
        
        fillTable();
    }
    
    
    /**
     * method that fills our table with required data
     */
    private void fillTable()
    {
        //creates a default table model and pulls it from our table
        DefaultTableModel dtm = (DefaultTableModel)orderTbl.getModel();
        //creates a hashmap of orderlines and populates it with the orderlines in our order
        HashMap<Integer, OrderLine> orderLines = order.getOrderLines();
        
        //for each orderline in our hashmap
        for(Integer key : orderLines.keySet())
        {
            //we create a string array and set the elements to the desired output
            String[] data = new String[4];
            double price = orderLines.get(key).getLineTotal();
            data[0] = "" + orderLines.get(key).getProduct().getProductID();
                    
            data[1] = "" + orderLines.get(key).getProduct().getProductName();
            
            data[2] = "£" + String.format("%.2f", price);

            data[3] = "" + orderLines.get(key).getQuantity();
            
            //we add the orderline to our model
            dtm.addRow(data);
        }
        
        //we set the model to our table
        orderTbl.setModel(dtm);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderTbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 600));

        BackBtn.setText("RETURN TO ORDERS");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        orderTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product", "Price", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(orderTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackBtn)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        //creates new view orders form passing in our logged in customer and our shopping basket
        ViewOrders vo = new ViewOrders(cust, basket);
        //closes existing form
        this.dispose();
        //sets new form to visible
        vo.setVisible(true);
    }//GEN-LAST:event_BackBtnActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAnOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAnOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAnOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAnOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAnOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable orderTbl;
    // End of variables declaration//GEN-END:variables
}
