/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.*;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * @date 22/02/2018 - commented - sr
 * @author Stuart Reid
 */
public class ViewBasket extends javax.swing.JFrame {

    //global variable for our logged in customer
    Customer cust;
    //global variable for our shopping basket
    HashMap<Integer, OrderLine> basket;
    

    /**
     * Creates new form ViewBasket
     * initialises components - sets cust to null
     */
    public ViewBasket() {
        initComponents();
        cust = null;
    } 
    
 
    /**
     * Creates new form ViewBasket
     * initialises components - maps parameters to our global variables
     * checks if any items have been added to basket and displays relevant information
     * @param cust - parameter holding our logged in customer
     * @param basket - hashmap of orderlines holding our shopping basket
     */
    public ViewBasket(Customer cust,HashMap<Integer,OrderLine> basket)
    {
        initComponents();
        this.cust = cust;
        this.basket = basket;
        
        if(basket.isEmpty())
        {
            infoBox("The basket is empty!\nPlease click \"ADD MORE PRODUCTS\" to continue shoping!","BASKET");
        }
        else
        { 
           fillTable();
        }
    }


    /**
     * method calculating the total cost of the basket
     */    
    private void calcTotal()
    {
        //double to hold our running total
        double total = 0;
        
        //loops through hashmap
        for(Integer key : basket.keySet())
        {
            //adds total for current orderline to running total
            total = total + (basket.get(key).getProduct().getPrice() * basket.get(key).getQuantity());
        }
        
        //displays total
        totValueLbl.setText("£" + String.format("%.2f", total));
    }
    
    
    /**
     * method that fills our table with desired values
     */
    private void fillTable()
    {
        //creates default table model and pulls the existing model from our table entity
        DefaultTableModel tableModel = (DefaultTableModel)bsktTbl.getModel();

        //loops hashmap
        for(Integer key : basket.keySet())
        {
            //ctring array for adding row
            String[] data = new String[5];
            //values mapped to array elements
            double price = basket.get(key).getProduct().getPrice();
            data[0] = "" + basket.get(key).getProductLineID();
            data[1] = "" + basket.get(key).getProduct().getProductID() + "";
            data[2] = "" + basket.get(key).getProduct().getProductName() + "";
            data[3] = "£" + String.format("%.2f", price);
            data[4] = "" + basket.get(key).getQuantity() + "";

            //array added to table model
            tableModel.addRow(data);
        }

        //calulating total method called
        calcTotal();

        //sets table model to our table
        bsktTbl.setModel(tableModel);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        bsktTbl = new javax.swing.JTable();
        addBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        buyBtn = new javax.swing.JButton();
        totHeadingLbl = new javax.swing.JLabel();
        totValueLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 600));

        bsktTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Row ID", "Product ID", "Product", "Price", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(bsktTbl);

        addBtn.setText("ADD MORE PRODUCTS");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        removeBtn.setText("REMOVE SELECTED PRODUCTS");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        buyBtn.setText("BUY");
        buyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyBtnActionPerformed(evt);
            }
        });

        totHeadingLbl.setText("TOTAL:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(buyBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(removeBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(addBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(41, 41, 41)
                        .addComponent(totHeadingLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totValueLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(totHeadingLbl)
                    .addComponent(totValueLbl))
                .addGap(18, 18, 18)
                .addComponent(removeBtn)
                .addGap(18, 18, 18)
                .addComponent(buyBtn)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * on click for our add button
     * @param evt 
     */
    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        //creates new view orders form passing in our logged in customer and our shopping basket
        ViewProducts view = new ViewProducts(cust, basket);
        //closes existing form
        this.dispose();
        //sets new form to visible
        view.setVisible(true);        
    }//GEN-LAST:event_addBtnActionPerformed

    
    /**
     * on click event for our remove button
     * @param evt 
     */
    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        //if a row is selected
        if(bsktTbl.getSelectedRow() != -1)
        {
            //creates default table model and pulls the existing model from our table entity
            DefaultTableModel dtm = (DefaultTableModel)bsktTbl.getModel();
            //if basket is not empty
            if(dtm.getRowCount() != 0)
            {
            //creates in pulling in value from our table
            int row = bsktTbl.getSelectedRow();
            //sets value for id collum to a string
            String idValue = bsktTbl.getValueAt(row, 0).toString();
            //parses string to an integer
            int id = Integer.parseInt(idValue);
            //removes orderline from our hashmap
            basket.remove(id);
            //removes  row from our table model
            dtm.removeRow(row);
            //sets table model to our table entity
            bsktTbl.setModel(dtm);
            //calls our calucate total method
            calcTotal();
            }
            //if basket is empty
            else
            {
                //error message pop up
                infoBox("The basket is empty!\nPlease click \"ADD MORE PRODUCTS\" to continue shoping!","BASKET");
            }
        }
        //if there is no row selected
        else
        {
            //error message pop up
            infoBox("Please select the row you would like to remove from your basket!","BASKET");
        }
    }//GEN-LAST:event_removeBtnActionPerformed

    
    /**
     * on click for our buy button
     * @param evt 
     */
    private void buyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyBtnActionPerformed
        //if no customer is logged in
        if(cust == null)
        {
            //error message displayed
            infoBox("Please log in to process your order\nIf you do not have an account you will be required to register one!\nPlease close this box to continue.","LOGIN");
            //creates new login form passing in our shopping basket
            CustomerLogin login = new CustomerLogin(basket);
            //closes existing form
            this.dispose();
            //sets new form to visible
            login.setVisible(true);
        }
        //if customer is logged in
        else
        {
            //creates DB manager
            DBManager db = new DBManager();
            //creates new date
            Date date = new Date();
            //gets value from our label and stores in a string
            String value = totValueLbl.getText().substring(1);
            //creates an order passing in our overloaded constructor
            Order ord = new Order(db.getNextOrderID(),cust.getUserID(), date, Double.parseDouble(value), "Paid", basket);
            //saves order to our database
            db.saveOrder(ord);
            //adds order to our customer order hashmap
            cust.addOrder(ord);
            
            //for each orderline in out basket hashmap
            for(int key : basket.keySet())
            {
                //add orderID to our orderlines
                db.addOrderID(key, ord.getOrderID());
                //adjust stock levels
                db.adjustStockLevel(basket.get(key).getProduct().getProductID(), basket.get(key).getQuantity());
            }

            //creates new confirmation form passing in our logged in customer
            Confirmation conf = new Confirmation (cust);
            //closes existing form
            this.dispose();
            //sets new form to visible
            conf.setVisible(true);
        }
    }//GEN-LAST:event_buyBtnActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBasket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBasket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBasket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBasket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBasket().setVisible(true);
            }
        });
    }

    
    /**
     * Method defining our pop up box
     * @param infoMessage - holds the body of our message
     * @param titleBar  - holds the title of the info box
     */   
    public static void infoBox(String infoMessage, String titleBar)
    {
        JOptionPane.showMessageDialog(null, infoMessage, "InfoBox: " + titleBar, JOptionPane.INFORMATION_MESSAGE);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTable bsktTbl;
    private javax.swing.JButton buyBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeBtn;
    private javax.swing.JLabel totHeadingLbl;
    private javax.swing.JLabel totValueLbl;
    // End of variables declaration//GEN-END:variables
}
